name: flutter_android_downloader
description: A plugin that uses the Android download manager
version: 1.0.1
homepage: https://github.com/mrdong916/flutter_android_downloader

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: com.bzqll.flutter_android_downloader
        pluginClass: FlutterAndroidDownloaderPlugin
